version: "3"

services:
  post:
    image: miguels007/post-service-img
    container_name: post-service
    ports:
      - "8080:8080"
  posts:
    image: miguels007/posts-service-img
    container_name: posts-service
    ports:
      - "8081:8080"
  user:
    image: juliancs21/userservice
    container_name: user-service
    ports:
      - "8082:8080"
  db:
    image: mongo:3.6.1
    container_name: postsdb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: